### ISSUE TITLE
ProfileGeneric class reset and capture methods

### ISSUE THREAD

**Issue by bavitus92** [pwitab/dlms-cosem#40]
Hello

Reset and capture methods of  ProfileGeneric class are void. It it possible to implement them?
Regards

**Comment by Krolken** [comment]
Hi

I'm working on a better API to interact with a meter over the interfaces. But there is quite alot of ground work to be done first.

But there should't be any limitation to run the action service on a method.

Ex:

```python

client.action(
        method=cosem.CosemMethod(
            interface=enumerations.CosemInterface.PROFILE_GENERIC,
            instance=cosem.Obis(a=0, b=5, c=25, d=9, e=0, f=255),
            method=1,
        ),
        data=b"\x12\x00\x00",
    )
```

**Comment by Krolken** [comment]
I'm gonna close this since it is a feature far in the future. As of now you need to use the lower level actions.
