### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by jbonde** [pwitab/dlms-cosem#59]
Can't get the installation to work. Tried pip, pip3, upgrading pip, manual installation of rust as well as the different suggestions after installation. Result shows 
Python: 3.9.2
platform: Linux-5.15.61-v7l+-armv7l-with-glibc2.31
pip: n/a
setuptools: 65.6.3
setuptools_rust: 1.5.2
rustc: 1.66.0 (69f9c33d7 2022-12-12)

 error: command '/usr/bin/arm-linux-gnueabihf-gcc' failed with exit code 1
      [end of output]
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for cryptography
Failed to build cryptography
ERROR: Could not build wheels for cryptography, which is required to install pyproject.toml-based projects

Any further suggestions?

**Comment by Krolken** [comment]
Not really. I have tests for python 3.9 in the current development branch so should not be a problem in python.

I would assume it has something to do with `arm7` architecture. I found this on cryptographys issue tracker: https://github.com/pyca/cryptography/issues/6347

**Comment by Krolken** [comment]
closing du to inactivity
