### ISSUE TITLE
ImportError: cannot import name 'WrapperHeader' from 'dlms'

### ISSUE THREAD

**Issue by Snappyfeet** [pwitab/dlms-cosem#65]
I have been trying to use this but every time i run "examples/dlms_with_tcp_example.py" , i get this error:
from dlms_cosem import WrapperHeader
ImportError: cannot import name 'WrapperHeader' from 'dlms_cosem'

I tried changing dlms to dlms_cosem, but the problem still persists. Is there any other version that supports WrapperHeader?

**Comment by Krolken** [comment]
Have you installed from source or are you installing from pypi?

Can you add the whole traceback? Seem like there is a code error but I am wondering why I have not gotten that in production?

**Comment by Snappyfeet** [comment]
when i installed this via pip, the version that got downloaded was a older version. I then downloaded the latest dlms-cosem version and the issue got resolved.
