### ISSUE TITLE
Could not perform GET request: <DataAccessResult.OBJECT_UNAVAILABLE: 11>

### ISSUE THREAD

**Issue by Snappyfeet** [pwitab/dlms-cosem#66]
when i ran the code, i got this error "raise DataResultError(
dlms_cosem.client.DataResultError: Could not perform GET request: <DataAccessResult.OBJECT_UNAVAILABLE: 11>". 
I tried everything but just couldn't resolve it.

**Comment by Snappyfeet** [comment]
this happened when i tried to run "python3 dlms_with_tcp_example.py" in my linux terminal, root privilege

**Comment by Krolken** [comment]
You are not able to read the object because it does not exist in the meter. At least in the association you are using.

**Comment by Snappyfeet** [comment]
that’s what even i thought but then i changed the obis code to the one being shown on the meter’s interface, it still gave me this error

**Comment by Krolken** [comment]
OK. Have you done any modification to the code? 
The code assumes and IDIS compilant meter and the encryption keys used are the keys for our lab-meter. 

If you have not changed anything it wont work anyway. I am assuming that you are using a meter the does not have encryption and when you are trying to read the invocation counter with the public client assoication you get this error.

You need to send the log so it shows what object you are trying to read and what state the connection is in.
