### ISSUE TITLE
dlms_cosem.client import not working

### ISSUE THREAD

**Issue by scratch** [pwitab/dlms-cosem#67]
(base) anon$:~/anaconda3/lib/python3.10/site-packages/dlms_cosem$ python
Python 3.10.9 (main, Mar  1 2023, 18:23:06) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from dlms_cosem import cosem, enumerations, utils, security
>>> from dlms_cosem.client import DlmsClient
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'dlms_cosem.client'

**Comment by scratch** [comment]
Should be:
from dlms_cosem.clients.dlms_client import DlmsClient

**Comment by Krolken** [comment]
test installing prerelease.

`pip install dlms-cosem --pre`
